# Generated by Django 5.0.6 on 2026-08-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(choices=[('Dubai', 'Dubai'), ('Abu Dhabi', 'Abu Dhabi'), ('Sharjah', 'Sharjah'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Ajman', 'Ajman')], default='Dubai', max_length=100),
        ),
    ]
