# Generated by Django 5.0.6 on 2026-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='developer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Use this to prioritize which developers appear first across the site.'),
        ),
    ]
