# Generated by Django 5.0.6 on 2026-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Wolves Real Estate', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/favicon/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Dubai', max_length=100)),
                ('country', models.CharField(default='UAE', max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('rera_number', models.CharField(blank=True, max_length=100)),
                ('trade_license', models.CharField(blank=True, max_length=100)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('header_scripts', models.TextField(blank=True)),
                ('footer_scripts', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
