# Generated by Django 5.0.6 on 2026-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Wolves International', max_length=200),
        ),
    ]
