# Generated by Django 5.0.6 on 2026-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_sitesettings_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
