# Generated by Django 5.0.6 on 2026-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_sitesettings_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='toll_free_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
