# Generated by Django 5.0.6 on 2026-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dld_permit_number',
            field=models.CharField(blank=True, help_text='Dubai Land Department permit/listing number', max_length=50),
        ),
    ]
