# Generated by Django 5.0.6 on 2026-07-28 11:36

from django.db import migrations, models


def copy_bedrooms_to_range(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    Property.objects.update(min_bedrooms=models.F('bedrooms'), max_bedrooms=models.F('bedrooms'))


def copy_range_to_bedrooms(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    Property.objects.update(bedrooms=models.F('min_bedrooms'))


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_dld_permit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='min_bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(copy_bedrooms_to_range, copy_range_to_bedrooms),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
    ]
