# Generated by Django 5.0.6 on 2026-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_bedrooms_property_max_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='properties/floor_plans/pdf/'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/floor_plans/'),
        ),
    ]
