# Generated by Django 5.0.6 on 2026-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_floorplan_pdf_alter_floorplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='handover_date',
            field=models.DateField(blank=True, help_text='Expected/actual handover date (mainly for off-plan properties)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_area',
            field=models.CharField(blank=True, help_text='e.g. "Close to Downtown Dubai and DIFC"', max_length=255),
        ),
    ]
