# Generated by Django 5.0.6 on 2026-08-19 07:26

from django.db import migrations, models


def blank_out_nearby_area(apps, schema_editor):
    # Existing rows hold '' (CharField default) which isn't valid JSON — on
    # MySQL, altering straight to a JSON column would fail validating that
    # value. Normalize to an empty list first so the type change is safe
    # regardless of backend (SQLite doesn't enforce this, but it's free
    # insurance either way).
    Property = apps.get_model('properties', 'Property')
    Property.objects.filter(nearby_area='').update(nearby_area='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_type_multiselect'),
    ]

    operations = [
        migrations.RunPython(blank_out_nearby_area, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='property',
            name='nearby_area',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
