# Generated by Django 5.0.6 on 2026-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_nearby_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('off_plan', 'Off Plan'), ('resale', 'Resale/Ready to Move'), ('rental', 'Rental')], max_length=20),
        ),
    ]
