# Generated by Django 5.0.6 on 2026-08-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Ajman', 'Ajman'), ('Dubai', 'Dubai'), ('Dubailand', 'Dubailand'), ('Palm Jumeirah', 'Palm Jumeirah'), ('Ras Al Khaimah, UAE', 'Ras Al Khaimah, UAE'), ('Sharjah', 'Sharjah'), ('Umm Al Quwain, UAE', 'Umm Al Quwain, UAE')], default='Dubai', max_length=100),
        ),
    ]
