# Generated by Django 5.0.6 on 2026-07-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('lead_type', models.CharField(choices=[('contact', 'Contact'), ('property_inquiry', 'Property Inquiry'), ('schedule_visit', 'Schedule Visit'), ('mortgage', 'Mortgage Inquiry'), ('newsletter', 'Newsletter'), ('brochure', 'Brochure Download'), ('career', 'Career Application'), ('general', 'General')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('unqualified', 'Unqualified')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Website, Google, Social, etc.', max_length=100)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='leads/resumes/')),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_newsletter', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agents.agent')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
