# Generated by Django 5.0.6 on 2026-08-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitted_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitted_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitted_bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitted_bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitted_property_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='submitted_purpose',
            field=models.CharField(blank=True, help_text='sale or rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('property_inquiry', 'Property Inquiry'), ('schedule_visit', 'Schedule Visit'), ('mortgage', 'Mortgage Inquiry'), ('newsletter', 'Newsletter'), ('brochure', 'Brochure Download'), ('career', 'Career Application'), ('general', 'General'), ('sell_property', 'List Your Property')], default='general', max_length=30),
        ),
    ]
