# Generated by Django 5.0.6 on 2026-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_url', models.CharField(max_length=500, unique=True)),
                ('to_url', models.CharField(max_length=500)),
                ('redirect_type', models.CharField(choices=[('301', 'Permanent (301)'), ('302', 'Temporary (302)')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'redirects',
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(help_text='e.g. home, about, properties', max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/')),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/')),
                ('schema_markup', models.JSONField(blank=True, null=True)),
                ('robots', models.CharField(default='index, follow', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'db_table': 'seo_pages',
            },
        ),
    ]
