# Generated by Django 5.0.6 on 2026-07-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['-created_at']},
        ),
    ]
